[build]
  command = "npm run build"
  publish = "build/client"

[functions]
  directory = "build/server"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200